on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build
      - run: python -m pip install -r requirements.txt
      - run: git clone https://github.com/qemu/qemu.git qemu
      - run: git -C qemu switch refs/tags/v8.1.2 -c v8.1.2
      - run: cd qemu && ./configure
      - run: make -C qemu
